### ISSUE TITLE
unable to get the code to work

### ISSUE THREAD

**Issue by Solarbytes** [intrbiz/hs110#2]
Hi Chris,

I am working on a home automation project and found your Github page for the HS110Client control software. Thank you very much for sharing the code in a public license 😊

I have integrated the code in an Android App but am unable to get it to work. The App compiles without errors but every time I try to use “consumption() or any other function it triggers an exception and I cannot figure out the reason.

Before I go into some detail, let me tell you that I am a rookie developer, this is my first app, fully self-taught developer so the reason for the failure is probably related to my inexperience…

Essentially, all I need to do it to get the current power usage of the plug so I can make calculations using that value, then turn the plug on or off based on those calculations.

In the section where you have an IP address starting with 10.xxxx defined, I updated that IP to the local IP of my HS110 plug and that is all I changed in the original code. Also, in case it matters, I have copied and pasted your code into my App as opposed to leaving it as an external resource as it was easier for me to implement.

Hereunder is how I instantiate the plug and try to get a reading of the power consumption:

The only time I am not triggering the exception is when I try to return the port number which successfully pops up the response “9999”, but that value is defined in the default attributes of the object, so I guess that is not a surprise.

HS110Client plug1 = new HS110Client("192.168.0.14");

try {
    HS110Client.GetRealtime response = plug1.consumption();
    Toast.makeText(getBaseContext(), "response.getPower returns this: "+response.getPower(), Toast.LENGTH_LONG).show();

} catch (Exception e) {
    e.printStackTrace();
    Toast.makeText(getBaseContext(), "exception occurred", Toast.LENGTH_LONG).show();
}

Any help would be much appreciated.

Thank you,
Gaetano.

**Comment by intrbiz** [comment]
Hi

Are you able to provide a stack trace?

I'm not very familiar with Android, but does you application have permission to open a TCP socket?

Chris

**Comment by Solarbytes** [comment]
Hi Chris,

I'll try opening a socket and will confirm back. I'll also look into capturing the stacktrace.

Cheers,
Gaetano.

Sent from my HTC

----- Reply message -----

**Comment by Solarbytes** [comment]
The issue is that I am running a network call on the main UI thread (NetworkOnMainThread is what exception "e" returns). To solve this I need to package the call in an AsyncTask. I will confirm once i can get it to work.

**Comment by Solarbytes** [comment]
OK, so I am now past the Network exception but the readings return "null" even though the plug is in use. Here is how I instantiate the HS110Client and try to get a reading. Does this look OK or am I making an invalid call?

Also, for memory, I did change the IP address that was hard-coded in your java file - I replaced it with the IP address of my plug. Is that what I should be doing?

public class AsyncReadPlug extends AsyncTask<String, String,String>  {

        HS110Client plug1 = new HS110Client("192.168.0.14");
            @Override
            protected String doInBackground(String... params) {

                    try {                        
                        HS110Client.GetRealtime response = plug1.consumption();
                        plugPower = Double.toString(response.getPower());
                       
                    } catch (Exception e) {
                        e.printStackTrace();                       
                    }
                return plugPower;
            }


            @Override
            protected void onPostExecute(String result) {
                TextView txt = (TextView) findViewById(R.id.fieldAvailPower);
                txt.setText(plugPower);
                Toast.makeText(getBaseContext(),"the variable plugPower equals "+plugPower, Toast.LENGTH_LONG).show();
            }

**Comment by jabrena** [comment]
Did you solve the problem?
In my case, I use the library without any problem on OSX and ARM devices.

Juan Antonio
